var Module = function(Module) {
  Module = Module || {};

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var n={},r;for(r in c)c.hasOwnProperty(r)&&(n[r]=c[r]);var u=!1,v=!1,w=!1,aa=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)u=!0;else if("WORKER"===c.ENVIRONMENT)v=!0;else if("NODE"===c.ENVIRONMENT)w=!0;else if("SHELL"===c.ENVIRONMENT)aa=!0;else throw Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.");else u="object"===typeof window,v="function"===typeof importScripts,w="object"===typeof process&&"function"===typeof require&&!u&&!v,aa=!u&&!w&&!v;
if(w){c.print||(c.print=console.log);c.printErr||(c.printErr=console.warn);var ba,ca;c.read=function(a,b){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};c.thisProgram||(c.thisProgram=1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof
x))throw a;});process.on("unhandledRejection",function(){process.exit(1)});c.inspect=function(){return"[Emscripten Module object]"}}else if(aa)c.print||(c.print=print),"undefined"!=typeof printErr&&(c.printErr=printErr),c.read="undefined"!=typeof read?function(a){return read(a)}:function(){throw"no read() available";},c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?
c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(u||v)c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=
function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},"undefined"!=typeof arguments&&(c.arguments=arguments),"undefined"!==typeof console?(c.print||(c.print=function(a){console.log(a)}),c.printErr||(c.printErr=function(a){console.warn(a)})):c.print||(c.print=function(){}),"undefined"===typeof c.setWindowTitle&&(c.setWindowTitle=function(a){document.title=a});else throw Error("Unknown runtime environment. Where are we?");c.print||(c.print=function(){});
c.printErr||(c.printErr=c.print);c.arguments||(c.arguments=[]);c.thisProgram||(c.thisProgram="./this.program");c.quit||(c.quit=function(a,b){throw b;});c.print=c.print;c.printErr=c.printErr;c.preRun=[];c.postRun=[];for(r in n)n.hasOwnProperty(r)&&(c[r]=n[r]);n=void 0;function da(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ea=0;function assert(a,b){a||y("Assertion failed: "+b)}var fa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
var buffer,ha,z,ia,ja,A,B,ka,la;function ma(){c.HEAP8=ha=new Int8Array(buffer);c.HEAP16=ia=new Int16Array(buffer);c.HEAP32=A=new Int32Array(buffer);c.HEAPU8=z=new Uint8Array(buffer);c.HEAPU16=ja=new Uint16Array(buffer);c.HEAPU32=B=new Uint32Array(buffer);c.HEAPF32=ka=new Float32Array(buffer);c.HEAPF64=la=new Float64Array(buffer)}var na,D,oa,pa,qa,ra,sa,ta;na=D=pa=qa=ra=sa=ta=0;oa=!1;
function ua(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+E+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var va=c.TOTAL_STACK||5242880,E=c.TOTAL_MEMORY||16777216;E<va&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+E+"! (TOTAL_STACK="+va+")");
c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:E/65536,maximum:E/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(E),c.buffer=buffer);ma();A[0]=1668509029;ia[1]=25459;if(115!==z[2]||99!==z[3])throw"Runtime error: expected the system to be little-endian!";
function F(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.B;"number"===typeof d?void 0===b.F?c.dynCall_v(d):c.dynCall_vi(d,b.F):d(void 0===b.F?null:b.F)}}}var wa=[],xa=[],ya=[],za=[],Aa=[],Ba=!1;function Ca(){var a=c.preRun.shift();wa.unshift(a)}var G=0,Da=null,Ea=null;c.preloadedImages={};c.preloadedAudios={};
function Fa(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(g){y(g)}}function b(){return c.wasmBinary||!u&&!v||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){k=a.exports;if(k.memory){a=k.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;ma()}c.asm=k;c.usingWasm=!0;G--;c.monitorRunDependencies&&c.monitorRunDependencies(G);0==G&&(null!==Da&&(clearInterval(Da),Da=null),Ea&&(a=Ea,Ea=null,a()))}
function e(a){d(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);y(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;G++;c.monitorRunDependencies&&c.monitorRunDependencies(G);
if(c.instantiateWasm)try{return c.instantiateWasm(h,d)}catch(rb){return c.printErr("Module.instantiateWasm callback failed with error: "+rb),!1}c.wasmBinary||"function"!==typeof WebAssembly.Y||Fa(f)||"function"!==typeof fetch?g(e):WebAssembly.Y(fetch(f,{credentials:"same-origin"}),h).then(e).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="aubio.wast",f="aubio.wasm",l="aubio.temp.asm.js";"function"===typeof c.locateFile&&
(Fa(e)||(e=c.locateFile(e)),Fa(f)||(f=c.locateFile(f)),Fa(l)||(l=c.locateFile(l)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:c},k=null;c.asmPreload=c.asm;var m=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===p)var b=m(a);else a:{var d=c.usingWasm?65536:16777216;0<a%d&&(a+=d-a%d);d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(t){b=null;break a}b=
void 0}return b};var p="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=d(b))||y("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");
return b}})();na=1024;D=na+9600;xa.push({B:function(){Ga()}},{B:function(){Ha()}},{B:function(){Ia()}},{B:function(){Ja()}});c.STATIC_BASE=na;c.STATIC_BUMP=9600;D+=16;var H=0;function I(){H+=4;return A[H-4>>2]}var Ka={};
function J(a,b){H=b;try{var d=I(),e=I(),f=I();a=0;J.buffer||(J.M=[null,[],[]],J.P=function(a,b){var d=J.M[a];assert(d);if(0===b||10===b){a=1===a?c.print:c.printErr;a:{for(var e=b=0;d[e];)++e;if(16<e-b&&d.subarray&&fa)b=fa.decode(d.subarray(b,e));else for(e="";;){var f=d[b++];if(!f){b=e;break a}if(f&128){var k=d[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var l=d[b++]&63;if(224==(f&240))f=(f&15)<<12|k<<6|l;else{var h=d[b++]&63;if(240==(f&248))f=(f&7)<<18|k<<12|l<<6|h;else{var Za=
d[b++]&63;if(248==(f&252))f=(f&3)<<24|k<<18|l<<12|h<<6|Za;else{var m=d[b++]&63;f=(f&1)<<30|k<<24|l<<18|h<<12|Za<<6|m}}}65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}}a(b);d.length=0}else d.push(b)});for(b=0;b<f;b++){for(var l=A[e+8*b>>2],h=A[e+(8*b+4)>>2],k=0;k<h;k++)J.P(d,z[l+k]);a+=h}return a}catch(m){return"undefined"!==typeof FS&&m instanceof FS.I||y(m),-m.K}}
function La(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ma=void 0;function K(a){for(var b="";z[a];)b+=Ma[z[a++]];return b}var L={},N={},Na={};function Oa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Pa(a,b){a=Oa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Qa(a){var b=Error,d=Pa(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});d.prototype=Object.create(b.prototype);d.prototype.constructor=d;d.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return d}
var O=void 0;function P(a){throw new O(a);}var Ra=void 0;function Sa(a){throw new Ra(a);}function Ta(a,b,d){function e(b){b=d(b);b.length!==a.length&&Sa("Mismatched type converter count");for(var e=0;e<a.length;++e)Q(a[e],b[e])}a.forEach(function(a){Na[a]=b});var f=Array(b.length),l=[],h=0;b.forEach(function(a,b){N.hasOwnProperty(a)?f[b]=N[a]:(l.push(a),L.hasOwnProperty(a)||(L[a]=[]),L[a].push(function(){f[b]=N[a];++h;h===l.length&&e(f)}))});0===l.length&&e(f)}
function Q(a,b,d){d=d||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||P('type "'+e+'" must have a positive integer typeid pointer');if(N.hasOwnProperty(a)){if(d.X)return;P("Cannot register type '"+e+"' twice")}N[a]=b;delete Na[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(function(a){a()}))}function Ua(a){P(a.a.f.b.name+" instance already deleted")}var Va=void 0,Wa=[];
function Xa(){for(;Wa.length;){var a=Wa.pop();a.a.s=!1;a["delete"]()}}function R(){}var Ya={};function $a(a,b,d){if(void 0===a[b].j){var e=a[b];a[b]=function(){a[b].j.hasOwnProperty(arguments.length)||P("Function '"+d+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].j+")!");return a[b].j[arguments.length].apply(this,arguments)};a[b].j=[];a[b].j[e.A]=e}}
function ab(a,b){c.hasOwnProperty(a)?(P("Cannot register public name '"+a+"' twice"),$a(c,a,a),c.hasOwnProperty(void 0)&&P("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),c[a].j[void 0]=b):c[a]=b}function bb(a,b,d,e,f,l,h,k){this.name=a;this.constructor=b;this.u=d;this.o=e;this.i=f;this.T=l;this.w=h;this.S=k;this.$=[]}
function cb(a,b,d){for(;b!==d;)b.w||P("Expected null or instance of "+d.name+", got an instance of "+b.name),a=b.w(a),b=b.i;return a}function db(a,b){if(null===b)return this.G&&P("null is not a valid "+this.name),0;b.a||P('Cannot pass "'+S(b)+'" as a '+this.name);b.a.c||P("Cannot pass deleted object as a pointer of type "+this.name);return cb(b.a.c,b.a.f.b,this.b)}
function eb(a,b){if(null===b){this.G&&P("null is not a valid "+this.name);if(this.D){var d=this.aa();null!==a&&a.push(this.o,d);return d}return 0}b.a||P('Cannot pass "'+S(b)+'" as a '+this.name);b.a.c||P("Cannot pass deleted object as a pointer of type "+this.name);!this.C&&b.a.f.C&&P("Cannot convert argument of type "+(b.a.h?b.a.h.name:b.a.f.name)+" to parameter type "+this.name);d=cb(b.a.c,b.a.f.b,this.b);if(this.D)switch(void 0===b.a.g&&P("Passing raw pointer to smart pointer is illegal"),this.da){case 0:b.a.h===
this?d=b.a.g:P("Cannot convert argument of type "+(b.a.h?b.a.h.name:b.a.f.name)+" to parameter type "+this.name);break;case 1:d=b.a.g;break;case 2:if(b.a.h===this)d=b.a.g;else{var e=b.clone();d=this.ba(d,T(function(){e["delete"]()}));null!==a&&a.push(this.o,d)}break;default:P("Unsupporting sharing policy")}return d}
function fb(a,b){if(null===b)return this.G&&P("null is not a valid "+this.name),0;b.a||P('Cannot pass "'+S(b)+'" as a '+this.name);b.a.c||P("Cannot pass deleted object as a pointer of type "+this.name);b.a.f.C&&P("Cannot convert argument of type "+b.a.f.name+" to parameter type "+this.name);return cb(b.a.c,b.a.f.b,this.b)}function gb(a){return this.fromWireType(B[a>>2])}function hb(a,b,d){if(b===d)return a;if(void 0===d.i)return null;a=hb(a,b,d.i);return null===a?null:d.S(a)}var ib={};
function lb(a,b){for(void 0===b&&P("ptr should not be undefined");a.i;)b=a.w(b),a=a.i;return ib[b]}function mb(a,b){b.f&&b.c||Sa("makeClassHandle requires ptr and ptrType");!!b.h!==!!b.g&&Sa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Object.create(a,{a:{value:b}})}
function U(a,b,d,e,f,l,h,k,m,p,g){this.name=a;this.b=b;this.G=d;this.C=e;this.D=f;this.Z=l;this.da=h;this.L=k;this.aa=m;this.ba=p;this.o=g;f||void 0!==b.i?this.toWireType=eb:(this.toWireType=e?db:fb,this.l=null)}function nb(a,b){c.hasOwnProperty(a)||Sa("Replacing nonexistant public symbol");c[a]=b;c[a].A=void 0}
function W(a,b){a=K(a);if(void 0!==c["FUNCTION_TABLE_"+a])var d=c["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)d=FUNCTION_TABLE[b];else{d=c.asm["dynCall_"+a];void 0===d&&(d=c.asm["dynCall_"+a.replace(/f/g,"d")],void 0===d&&P("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";d=(new Function("dynCall",
"rawFunction",f+"};\n"))(d,b)}"function"!==typeof d&&P("unknown function pointer with signature "+a+": "+b);return d}var ob=void 0;function pb(a){a=qb(a);var b=K(a);X(a);return b}function sb(a,b){function d(a){f[a]||N[a]||(Na[a]?Na[a].forEach(d):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(d);throw new ob(a+": "+e.map(pb).join([", "]));}function tb(a,b){for(var d=[],e=0;e<a;e++)d.push(A[(b>>2)+e]);return d}function ub(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function vb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var d=Pa(b.name||"unknownFunctionName",function(){});d.prototype=b.prototype;d=new d;a=b.apply(d,a);return a instanceof Object?a:d}var wb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function xb(a){4<a&&0===--Y[a].H&&(Y[a]=void 0,wb.push(a))}
function T(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=wb.length?wb.pop():Y.length;Y[b]={H:1,value:a};return b}}function S(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function yb(a,b){switch(b){case 2:return function(a){return this.fromWireType(ka[a>>2])};case 3:return function(a){return this.fromWireType(la[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function zb(a,b,d){switch(b){case 0:return d?function(a){return ha[a]}:function(a){return z[a]};case 1:return d?function(a){return ia[a>>1]}:function(a){return ja[a>>1]};case 2:return d?function(a){return A[a>>2]}:function(a){return B[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Z(a){a||P("Cannot use deleted val. handle = "+a);return Y[a].value}function Ab(a,b){var d=N[a];void 0===d&&P(b+" has unknown type "+pb(a));return d}
for(var Bb={},Cb=Array(256),Db=0;256>Db;++Db)Cb[Db]=String.fromCharCode(Db);Ma=Cb;O=c.BindingError=Qa("BindingError");Ra=c.InternalError=Qa("InternalError");R.prototype.isAliasOf=function(a){if(!(this instanceof R&&a instanceof R))return!1;var b=this.a.f.b,d=this.a.c,e=a.a.f.b;for(a=a.a.c;b.i;)d=b.w(d),b=b.i;for(;e.i;)a=e.w(a),e=e.i;return b===e&&d===a};
R.prototype.clone=function(){this.a.c||Ua(this);if(this.a.v)return this.a.count.value+=1,this;var a=this.a;a=Object.create(Object.getPrototypeOf(this),{a:{value:{count:a.count,s:a.s,v:a.v,c:a.c,f:a.f,g:a.g,h:a.h}}});a.a.count.value+=1;a.a.s=!1;return a};R.prototype["delete"]=function(){this.a.c||Ua(this);this.a.s&&!this.a.v&&P("Object already scheduled for deletion");--this.a.count.value;if(0===this.a.count.value){var a=this.a;a.g?a.h.o(a.g):a.f.b.o(a.c)}this.a.v||(this.a.g=void 0,this.a.c=void 0)};
R.prototype.isDeleted=function(){return!this.a.c};R.prototype.deleteLater=function(){this.a.c||Ua(this);this.a.s&&!this.a.v&&P("Object already scheduled for deletion");Wa.push(this);1===Wa.length&&Va&&Va(Xa);this.a.s=!0;return this};U.prototype.U=function(a){this.L&&(a=this.L(a));return a};U.prototype.J=function(a){this.o&&this.o(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=gb;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.D?mb(this.b.u,{f:this.Z,c:d,h:this,g:a}):mb(this.b.u,{f:this,c:a})}var d=this.U(a);if(!d)return this.J(a),null;var e=lb(this.b,d);if(void 0!==e){if(0===e.a.count.value)return e.a.c=d,e.a.g=a,e.clone();e=e.clone();this.J(a);return e}e=this.b.T(d);e=Ya[e];if(!e)return b.call(this);e=this.C?e.R:e.pointerType;var f=hb(d,this.b,e.b);return null===f?b.call(this):this.D?mb(e.b.u,{f:e,c:f,h:this,g:a}):mb(e.b.u,{f:e,c:f})};
c.getInheritedInstanceCount=function(){return Object.keys(ib).length};c.getLiveInheritedInstances=function(){var a=[],b;for(b in ib)ib.hasOwnProperty(b)&&a.push(ib[b]);return a};c.flushPendingDeletes=Xa;c.setDelayFunction=function(a){Va=a;Wa.length&&Va&&Va(Xa)};ob=c.UnboundTypeError=Qa("UnboundTypeError");c.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};assert(!oa);
var Eb=D;D=D+4+15&-16;ta=Eb;pa=qa=da(D);ra=pa+va;sa=da(ra);A[ta>>2]=sa;oa=!0;c.wasmTableSize=85;c.wasmMaxTableSize=85;c.N={};
c.O={abort:y,enlargeMemory:function(){ua()},getTotalMemory:function(){return E},abortOnCannotGrowMemory:ua,___setErrNo:function(a){c.___errno_location&&(A[c.___errno_location()>>2]=a);return a},___syscall140:function(a,b){H=b;try{var d=Ka.V();I();var e=I(),f=I(),l=I();FS.fa(d,e,l);A[f>>2]=d.position;d.W&&0===e&&0===l&&(d.W=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.I||y(h),-h.K}},___syscall146:J,___syscall54:function(a,b){H=b;return 0},___syscall6:function(a,b){H=b;try{var d=
Ka.V();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.I||y(e),-e.K}},__embind_register_bool:function(a,b,d,e,f){var l=La(d);b=K(b);Q(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===d)var e=ha;else if(2===d)e=ia;else if(4===d)e=A;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>l])},l:null})},__embind_register_class:function(a,b,d,e,f,l,
h,k,m,p,g,q,C){g=K(g);l=W(f,l);k&&(k=W(h,k));p&&(p=W(m,p));C=W(q,C);var t=Oa(g);ab(t,function(){sb("Cannot construct "+g+" due to unbound types",[e])});Ta([a,b,d],e?[e]:[],function(b){b=b[0];if(e){var d=b.b;var f=d.u}else f=R.prototype;b=Pa(t,function(){if(Object.getPrototypeOf(this)!==h)throw new O("Use 'new' to construct "+g);if(void 0===m.m)throw new O(g+" has no accessible constructor");var a=m.m[arguments.length];if(void 0===a)throw new O("Tried to invoke ctor of "+g+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(m.m).toString()+") parameters instead!");return a.apply(this,arguments)});var h=Object.create(f,{constructor:{value:b}});b.prototype=h;var m=new bb(g,b,h,C,d,l,k,p);d=new U(g,m,!0,!1,!1);f=new U(g+"*",m,!1,!1,!1);var q=new U(g+" const*",m,!1,!0,!1);Ya[a]={pointerType:f,R:q};nb(t,b);return[d,f,q]})},__embind_register_class_constructor:function(a,b,d,e,f,l){var h=tb(b,d);f=W(e,f);Ta([],[a],function(a){a=a[0];var d="constructor "+a.name;void 0===a.b.m&&(a.b.m=
[]);if(void 0!==a.b.m[b-1])throw new O("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.b.m[b-1]=function(){sb("Cannot construct "+a.name+" due to unbound types",h)};Ta([],h,function(e){a.b.m[b-1]=function(){arguments.length!==b-1&&P(d+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],h=Array(b);h[0]=l;for(var k=1;k<
b;++k)h[k]=e[k].toWireType(a,arguments[k-1]);h=f.apply(null,h);ub(a);return e[0].fromWireType(h)};return[]});return[]})},__embind_register_class_function:function(a,b,d,e,f,l,h,k){var m=tb(d,e);b=K(b);l=W(f,l);Ta([],[a],function(a){function e(){sb("Cannot call "+f+" due to unbound types",m)}a=a[0];var f=a.name+"."+b;k&&a.b.$.push(b);var p=a.b.u,t=p[b];void 0===t||void 0===t.j&&t.className!==a.name&&t.A===d-2?(e.A=d-2,e.className=a.name,p[b]=e):($a(p,b,f),p[b].j[d-2]=e);Ta([],m,function(e){var k=f,
g=a,m=l,q=e.length;2>q&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var t=null!==e[1]&&null!==g,C=!1;for(g=1;g<e.length;++g)if(null!==e[g]&&void 0===e[g].l){C=!0;break}var jb="void"!==e[0].name,M="",V="";for(g=0;g<q-2;++g)M+=(0!==g?", ":"")+"arg"+g,V+=(0!==g?", ":"")+"arg"+g+"Wired";k="return function "+Oa(k)+"("+M+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+k+" called with ' + arguments.length + ' arguments, expected "+(q-2)+
" args!');\n}\n";C&&(k+="var destructors = [];\n");var kb=C?"destructors":"null";M="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[P,m,h,ub,e[0],e[1]];t&&(k+="var thisWired = classParam.toWireType("+kb+", this);\n");for(g=0;g<q-2;++g)k+="var arg"+g+"Wired = argType"+g+".toWireType("+kb+", arg"+g+"); // "+e[g+2].name+"\n",M.push("argType"+g),m.push(e[g+2]);t&&(V="thisWired"+(0<V.length?", ":"")+V);k+=(jb?"var rv = ":"")+"invoker(fn"+(0<V.length?", ":"")+V+");\n";if(C)k+=
"runDestructors(destructors);\n";else for(g=t?1:2;g<e.length;++g)q=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==e[g].l&&(k+=q+"_dtor("+q+"); // "+e[g].name+"\n",M.push(q+"_dtor"),m.push(e[g].l));jb&&(k+="var ret = retType.fromWireType(rv);\nreturn ret;\n");M.push(k+"}\n");e=vb(M).apply(null,m);void 0===p[b].j?(e.A=d-2,p[b]=e):p[b].j[d-2]=e;return[]});return[]})},__embind_register_emval:function(a,b){b=K(b);Q(a,{name:b,fromWireType:function(a){var b=Y[a].value;xb(a);return b},toWireType:function(a,
b){return T(b)},argPackAdvance:8,readValueFromPointer:gb,l:null})},__embind_register_float:function(a,b,d){d=La(d);b=K(b);Q(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+S(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:yb(b,d),l:null})},__embind_register_integer:function(a,b,d,e,f){function l(a){return a}b=K(b);-1===f&&(f=4294967295);var h=La(d);if(0===e){var k=32-8*d;
l=function(a){return a<<k>>>k}}var m=-1!=b.indexOf("unsigned");Q(a,{name:b,fromWireType:l,toWireType:function(a,d){if("number"!==typeof d&&"boolean"!==typeof d)throw new TypeError('Cannot convert "'+S(d)+'" to '+this.name);if(d<e||d>f)throw new TypeError('Passing a number "'+S(d)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return m?d>>>0:d|0},argPackAdvance:8,readValueFromPointer:zb(b,h,0!==e),l:null})},__embind_register_memory_view:function(a,
b,d){function e(a){a>>=2;var b=B;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];d=K(d);Q(a,{name:d,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{X:!0})},__embind_register_std_string:function(a,b){b=K(b);Q(a,{name:b,fromWireType:function(a){for(var b=B[a>>2],d=Array(b),l=0;l<b;++l)d[l]=String.fromCharCode(z[a+4+l]);X(a);return d.join("")},toWireType:function(a,b){function d(a,b){return a[b]}function e(a,
b){return a.charCodeAt(b)}b instanceof ArrayBuffer&&(b=new Uint8Array(b));var h;b instanceof Uint8Array?h=d:b instanceof Uint8ClampedArray?h=d:b instanceof Int8Array?h=d:"string"===typeof b?h=e:P("Cannot pass non-string to std::string");var k=b.length,m=Fb(4+k);B[m>>2]=k;for(var p=0;p<k;++p){var g=h(b,p);255<g&&(X(m),P("String has UTF-16 code units that do not fit in 8 bits"));z[m+4+p]=g}null!==a&&a.push(X,m);return m},argPackAdvance:8,readValueFromPointer:gb,l:function(a){X(a)}})},__embind_register_std_wstring:function(a,
b,d){d=K(d);if(2===b){var e=function(){return ja};var f=1}else 4===b&&(e=function(){return B},f=2);Q(a,{name:d,fromWireType:function(a){for(var b=e(),d=B[a>>2],l=Array(d),p=a+4>>f,g=0;g<d;++g)l[g]=String.fromCharCode(b[p+g]);X(a);return l.join("")},toWireType:function(a,d){var k=e(),h=d.length,l=Fb(4+h*b);B[l>>2]=h;for(var g=l+4>>f,q=0;q<h;++q)k[g+q]=d.charCodeAt(q);null!==a&&a.push(X,l);return l},argPackAdvance:8,readValueFromPointer:gb,l:function(a){X(a)}})},__embind_register_void:function(a,b){b=
K(b);Q(a,{ea:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},__emval_as:function(a,b,d){a=Z(a);b=Ab(b,"emval::as");var e=[],f=T(e);A[d>>2]=f;return b.toWireType(e,a)},__emval_decref:xb,__emval_get_property:function(a,b){a=Z(a);b=Z(b);return T(a[b])},__emval_incref:function(a){4<a&&(Y[a].H+=1)},__emval_new_array:function(){return T([])},__emval_new_cstring:function(a){var b=Bb[a];return T(void 0===b?K(a):b)},__emval_new_object:function(){return T({})},__emval_run_destructors:function(a){ub(Y[a].value);
xb(a)},__emval_set_property:function(a,b,d){a=Z(a);b=Z(b);d=Z(d);a[b]=d},__emval_take_value:function(a,b){a=Ab(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},_abort:function(){c.abort()},_emscripten_memcpy_big:function(a,b,d){z.set(z.subarray(b,b+d),a);return a},DYNAMICTOP_PTR:ta,STACKTOP:qa};var Gb=c.asm(c.N,c.O,buffer);c.asm=Gb;
var Ja=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)},Ga=c.__GLOBAL__sub_I_fft_cc=function(){return c.asm.__GLOBAL__sub_I_fft_cc.apply(null,arguments)},Ia=c.__GLOBAL__sub_I_pitch_cc=function(){return c.asm.__GLOBAL__sub_I_pitch_cc.apply(null,arguments)},Ha=c.__GLOBAL__sub_I_tempo_cc=function(){return c.asm.__GLOBAL__sub_I_tempo_cc.apply(null,arguments)};c.___errno_location=function(){return c.asm.___errno_location.apply(null,arguments)};
var qb=c.___getTypeName=function(){return c.asm.___getTypeName.apply(null,arguments)},X=c._free=function(){return c.asm._free.apply(null,arguments)},Fb=c._malloc=function(){return c.asm._malloc.apply(null,arguments)};c.dynCall_ffii=function(){return c.asm.dynCall_ffii.apply(null,arguments)};c.dynCall_fi=function(){return c.asm.dynCall_fi.apply(null,arguments)};c.dynCall_fii=function(){return c.asm.dynCall_fii.apply(null,arguments)};c.dynCall_fiii=function(){return c.asm.dynCall_fiii.apply(null,arguments)};
c.dynCall_ii=function(){return c.asm.dynCall_ii.apply(null,arguments)};c.dynCall_iii=function(){return c.asm.dynCall_iii.apply(null,arguments)};c.dynCall_iiii=function(){return c.asm.dynCall_iiii.apply(null,arguments)};c.dynCall_iiiii=function(){return c.asm.dynCall_iiiii.apply(null,arguments)};c.dynCall_iiiiii=function(){return c.asm.dynCall_iiiiii.apply(null,arguments)};c.dynCall_v=function(){return c.asm.dynCall_v.apply(null,arguments)};
c.dynCall_vi=function(){return c.asm.dynCall_vi.apply(null,arguments)};c.dynCall_viii=function(){return c.asm.dynCall_viii.apply(null,arguments)};c.asm=Gb;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}x.prototype=Error();x.prototype.constructor=x;var Hb=null;Ea=function Ib(){c.calledRun||Jb();c.calledRun||(Ea=Ib)};
function Jb(){function a(){if(!c.calledRun&&(c.calledRun=!0,!ea)){Ba||(Ba=!0,F(xa));F(ya);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Aa.unshift(a)}F(Aa)}}null===Hb&&(Hb=Date.now());if(!(0<G)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ca();F(wa);0<G||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}c.run=Jb;c.exit=function(a,b){if(!b||!c.noExitRuntime||0!==a){if(!c.noExitRuntime&&(ea=!0,qa=void 0,F(za),c.onExit))c.onExit(a);w&&process.exit(a);c.quit(a,new x(a))}};function y(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";ea=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=y;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;Jb();


  return Module;
};
if (typeof module === "object" && module.exports) {
  module['exports'] = Module;
};
